<?php
namespace EAMann\Marmoset;

use Symfony\Component\Console\Command\Command as SCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * The actual wiring for the Symfony command.
 *
 * @package EAMann\Marmoset
 */
class Command extends SCommand {
	protected function configure() {
		$this->setName( 'run' )
			->setDescription( 'Make the monkeys type' )
			->addOption(
				'mode',
				null,
				InputOption::VALUE_OPTIONAL,
				'Run-mode',
				'synchronous'
			);
	}

	/**
	 * Actually execute the command
	 *
	 * @param InputInterface  $input
	 * @param OutputInterface $output
	 *
	 * @return null|int null or 0 if everything went fine, or an error code
	 */
	public function execute( InputInterface $input, OutputInterface $output ) {
		parent::execute( $input, $output ); // TODO: Change the autogenerated stub
	}
}